name: CI

on:
  push:
    branches: [ main, task-* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 src || true

      - name: Run tests
        run: |
          if [ -d "tests" ]; then
            pytest tests || true
          else
            echo "No tests directory found. Skipping tests."
          fi
